function mlaue(inifile)
%
% function mlaue(inifile)
%
% Interactive MATLAB GUI for displaying and manipulating
% neutron Laue images from VIVALDI.
% The input takes the form of TIFF files.
%
% Created by:  A.Wildes 14 October, 2006
% Last modified: ARW 13.8.07

%=============  Define window sizes ===============================
winpos=[10 10 1000 500];        % window size
impos=[0.04 0.05 0.94 0.7];      % Image size
Hd=[100 150 50 150 50];         % Horizontal widths of data information
Hi=[50 20];                   % Horizontal widths of intensity limits
V=[25 45 65 105];                         % Vertical heights
txtsze=[20];                    % Text size

%=============  Create control window =========================
hml_ctrl=findobj('tag','ml_ControlWindow');
mlaue_ver = '0.1 (October 14th 2006)';
if ~isempty(hml_ctrl) & hml_ctrl
  delete (hml_ctrl);
end
  hml_ctrl=figure('Tag','ml_ControlWindow',...
    'DefaultUicontrolBackgroundColor',[1 1 1],...
    'DefaultUicontrolForegroundColor',[0 0 0],...
    'DefaultUicontrolHorizontalAlignment','left',...
    'DeleteFcn','ml_exit',...
    'HandleVisibility','on',...
    'Position',winpos,...
    'MenuBar','none',...
    'NumberTitle','on',...
    'Name','MLAUE',...
    'Resize','off',...
    'Visible','off');

%===== CREATE MENUS ================================================
%===== File menu ===================================================
hfile=uimenu(hml_ctrl,'label','&File',...
    'tag','ml_FileMenu');
uimenu(hfile,'label','Load image',...
    'accelerator','l',...
    'callback','ml_load;');
uimenu(hfile,'label','Save file',...
    'accelerator','s',...
    'callback','ml_save;');
uimenu(hfile,'label','Exit',...
    'accelerator','q',...
    'callback','ml_exit;');
%===== Zoom menu ===================================================
hzoom=uimenu(hml_ctrl,'label','&Zoom',...
    'tag','ml_ZoomMenu');
uimenu(hzoom,'label','Zoom in',...
    'accelerator','z',...
    'callback','set(findobj(''tag'',''ml_ZoomRadio''),''Value'',1);ml_zoom;');
uimenu(hzoom,'label','Zoom off',...
    'callback','set(findobj(''tag'',''ml_ZoomRadio''),''Value'',0);ml_zoom;');
uimenu(hzoom,'label','Reset Zoom',...
    'callback','ml_load;');
%===== Image menu ===================================================
himage=uimenu(hml_ctrl,'label','&Image',...
    'tag','ml_ImageMenu',...
    'UserData','gray');
uimenu(himage,'label','Black on White',...
    'callback','set(findobj(''tag'',''ml_ImageMenu''),''UserData'',''gray'');colormap(gray);');
uimenu(himage,'label','White on black',...
    'callback','set(findobj(''tag'',''ml_ImageMenu''),''UserData'',''flipud(gray)'');colormap(flipud(gray));');
uimenu(himage,'label','Jet',...
    'callback','set(findobj(''tag'',''ml_ImageMenu''),''UserData'',jet);''colormap(jet)'';');
uimenu(himage,'label','Inverse Jet',...
    'callback','set(findobj(''tag'',''ml_ImageMenu''),''UserData'',''flipud(jet))'';colormap(flipud(jet));');

%===== CREATE LOAD AND SAVE =========================================
%---------------- 'Data Directory' title -----------------------
uicontrol(hml_ctrl,...
      'Style','text',...
      'String','Data Directory',...
      'BackgroundColor',get(0,'DefaultUicontrolBackgroundColor'), ...
      'ForegroundColor','k',...
      'Position',[2 winpos(4)-V(1) Hd(1) txtsze]);
%---------------- 'Data Directory' text box -----------------------
uicontrol(hml_ctrl,...
        'style','edit',...
        'tag','ml_DataDir',...
        'callback','ml_load;',...
        'Position',[Hd(1)+5 winpos(4)-V(1) Hd(2) txtsze]);
%---------------- 'Data File' title -----------------------
uicontrol(hml_ctrl,...
      'Style','text',...
      'String','Data file',...
      'BackgroundColor',get(0,'DefaultUicontrolBackgroundColor'), ...
      'ForegroundColor','k',...
      'Position',[2 winpos(4)-V(2) Hd(3) txtsze]);
%---------------- 'Data File' text box -----------------------
uicontrol(hml_ctrl,...
        'style','edit',...
        'tag','ml_DataFile',...
        'callback','ml_load;',...
        'Position',[Hd(1)+5 winpos(4)-V(2) Hd(4) txtsze]);
%---------------- New data file button -----------------------
uicontrol(hml_ctrl,...
      'Style','pushbutton',...
      'String','New...',...
      'Callback','[datafile, datadir]=uigetfile(''*.tif'');ml_load(datadir,datafile);',...
      'Position',[sum(Hd(1:2))+10 winpos(4)-V(2) Hd(5) txtsze]);

%===== CREATE IMAGE MANIPULATION BOXES =============================
%---------------- Min Intensity text -----------------------
uicontrol(hml_ctrl,...
      'Style','text',...
      'String','Intensity Min',...
      'BackgroundColor',get(0,'DefaultUicontrolBackgroundColor'), ...
      'ForegroundColor','k',...
      'Position',[5 winpos(4)-V(3)-5 Hi(1)+Hi(2) txtsze]);
%      'Position',[5 winpos(4)*(impos(2)+impos(4))+txtsze+2 Hi(1)+Hi(2) txtsze]);
%---------------- Min Intensity text box -------------------
uicontrol(hml_ctrl,...
        'style','edit',...
        'tag','ml_MinIntens',...
        'callback','ml_modplot',...
        'Position',[10+Hi(1)+Hi(2) winpos(4)-V(3)-5 Hi(1) txtsze]);
%---------------- Max Intensity text -----------------------
uicontrol(hml_ctrl,...
      'Style','text',...
      'String','Max',...
      'BackgroundColor',get(0,'DefaultUicontrolBackgroundColor'), ...
      'ForegroundColor','k',...
      'Position',[15+2*Hi(1)+Hi(2) winpos(4)-V(3)-5 Hi(1) txtsze]);
%---------------- Max Intensity text box -------------------
uicontrol(hml_ctrl,...
        'style','edit',...
        'tag','ml_MaxIntens',...
        'callback','ml_modplot',...
        'Position',[20+3*Hi(1)+Hi(2) winpos(4)-V(3)-5 Hi(1) txtsze]);
%---------------- Fix Intensities radio button ---------------------
hifrb=uicontrol(hml_ctrl,...
        'tag','ml_IntFix',...
        'String','Fix Intensities',...
        'style','radiobutton',...
        'callback','ml_modplot',...
        'Value',0,...
        'UserData',0,...
        'BackgroundColor',get(0,'DefaultUicontrolBackgroundColor'), ...
        'ForegroundColor','k',...
        'Position',[5 winpos(4)*(impos(2)+impos(4))+txtsze+2 100 txtsze]);
%---------------- Zoom in radio button ---------------------
hzrb=uicontrol(hml_ctrl,...
        'tag','ml_ZoomRadio',...
        'String','Zoom in',...
        'style','radiobutton',...
        'callback','ml_zoom',...
        'Value',0,...
        'UserData',0,...
        'BackgroundColor',get(0,'DefaultUicontrolBackgroundColor'), ...
        'ForegroundColor','k',...
        'Position',[40+4*Hi(1)+Hi(2) winpos(4)*(impos(2)+impos(4))+txtsze+2 75 txtsze]);
%---------------- Extract data button ----------------------
hzex=uicontrol(hml_ctrl,...
        'tag','ml_ExtractButton',...
        'String','Extract Data',...
        'style','pushbutton',...
        'callback','ml_exwin',...
        'Position',[40+4*Hi(1)+Hi(2)+80 winpos(4)*(impos(2)+impos(4))+txtsze+2 75 txtsze]);
%---------------- Reset Image button ------------------------
uicontrol(hml_ctrl,...
      'Style','pushbutton',...
      'String','Reset Image',...
      'callback','ml_load',...
      'Position',[40+4*Hi(1)+Hi(2)+160 winpos(4)*(impos(2)+impos(4))+txtsze+2 75 txtsze]);

    
%===== CREATE IMAGE WINDOW =========================================
hml_imwin = axes('Position',impos,...
                 'Tag','ml_ImageWindow');

%===== CREATE CUT WINDOW =========================================

%=============  Create control window =========================
set(hml_ctrl,'Visible','on','Position',winpos);


