function [order, optionx, appfcn, specfcn, optiony] = sp_opt(cmd)
% [order, optionx, appfcn, specfcn, optiony] = sp_opt(cmd)
% Options window for SSym

order=[]; optionx=[]; appfcn=[]; specfcn=[]; optiony=[];

if ~exist('cmd') | isempty(cmd)
	cmd = 'get';
end

if findstr(cmd,'force')
	delete(findobj('tag','hsp_opt'));
end

if isempty(findobj('tag','hsp_opt'))

	Fposl=200; Fposb=50; Fwidth=320; Fheight=150;
	hsp_opt = figure('Position',[Fposl Fposb Fwidth Fheight],...
		'Unit','pixel',...
		'Color',get(0,'DefaultUicontrolBackgroundColor'), ...
		'MenuBar','none',...
		'Name','SSym : Options',...
		'NumberTitle','off',...
		'Resize','off',...
                'Tag','hsp_opt', ...
		'Visible','off');

	uicontrol(hsp_opt,...		% select parts
		'String','Work on :',...
		'FontName','Times','FontSize',12,...
		'Position',[ 6 110 70 22],...
		'Style','text',...
		'ForegroundColor',[1 1 1],...
		'HorizontalAlignment','left');

	uicontrol(hsp_opt,...
		'Style','checkbox',....
		'Tag','hsp_obg',...
		'String','Backg',...
		'ForegroundColor','cyan',...
		'Value',1,...
		'Position',[ 4 92 70 20 ]);

	uicontrol(hsp_opt,...
		'Style','checkbox',....
		'Tag','hsp_oapp',...
		'String','App.',...
		'ForegroundColor','green',...
		'Value',1,...
		'Position',[ 4 70 70 20 ]);

	uicontrol(hsp_opt,...
		'Style','checkbox',....
		'Tag','hsp_osig',...
		'String','Signal',...
		'ForegroundColor','magenta',...
		'Value',1,...
		'Position',[ 4 48 70 20 ]);

	uicontrol(hsp_opt,...		% 
		'String','Functions :',...
		'FontName','Times','FontSize',12,...
		'Position',[ 80 92 70 22],...
		'Style','text',...
		'ForegroundColor',[1 1 1],...
		'HorizontalAlignment','left');

	uicontrol(hsp_opt,...		% app fcn
		'Style','edit',....
		'Tag','hsp_ofapp',...
		'String','gauss',...
		'BackgroundColor',[1 1 1],...
		'ForegroundColor',[0 0 0],...
		'Position',[ 80 70 70 20 ]);

	uicontrol(hsp_opt,...		% signal fcn
		'Style','edit',....
		'Tag','hsp_ofsig',...
		'String','lorz',...
		'BackgroundColor',[1 1 1],...
		'ForegroundColor',[0 0 0],...
		'Position',[ 80 48 70 20 ]);

	uicontrol(hsp_opt,...		% Main Frame
		'Style','Frame',...
		'Position',[ 235 45 80 100 ]);

	uicontrol(hsp_opt,...		% Main
		'String','Main',...
		'FontName','Times','FontSize',12,...
		'Position',[ 255 115 50 22],...
		'Style','text',...
		'ForegroundColor',[1 1 1],...
		'HorizontalAlignment','left');

	uicontrol(hsp_opt,...		% iterate
		'Style','checkbox',....
		'Tag','hsp_oiter',...
		'String','Iterative',...
		'Value',1,...
		'Position',[ 240 92 70 20 ]);

	uicontrol(hsp_opt,...		% Global/local fit
		'Style','popup',....
		'Tag','hsp_oglob',...
		'String','Global|Local',...
		'Value',1,...
		'Position',[ 240 70 70 20 ]);

	uicontrol(hsp_opt,...		% fit order
		'Style','popup',....
		'Tag','hsp_oord',...
		'String','Order 1|Order 2|Order 3|Order 4|MaxOrder',...
		'Value',2,...
		'Position',[ 240 48 70 20 ]);

	uicontrol(hsp_opt,...		% 
		'String','Apparatus',...
		'FontName','Times','FontSize',12,...
		'Position',[ 160 115 70 22],...
		'Style','text',...
		'ForegroundColor',[1 1 1],...
		'HorizontalAlignment','left');

	uicontrol(hsp_opt,...		% 
		'String','fit is :',...
		'FontName','Times','FontSize',12,...
		'Position',[ 180 92 50 22],...
		'Style','text',...
		'ForegroundColor',[1 1 1],...
		'HorizontalAlignment','left');

	uicontrol(hsp_opt,...		% Global/local app fit
		'Style','popup',....
		'Tag','hsp_ogapp',...
		'String','Local App|Global App',...
		'Value',1,...
		'Position',[ 160 70 70 20 ]);


% buttons : OK(hide), cancel, Compute

	uicontrol(hsp_opt,...
		'Style','PushButton',...
		'String','Ok',...
		'Callback','sp_opt(''hide'');',...
		'Position',[32 4 50 20]);
   	uicontrol(hsp_opt,...
		'Style','PushButton',...
		'String','Cancel',...
		'CallBack','delete(gcf)', ...
		'Position',[92 4 50 20]);

   	uicontrol(hsp_opt,...
		'Style','PushButton',...
		'String','Default',...
		'CallBack','sp_opt(''force+show'');', ...
		'Position',[152 4 50 20]);


else
	hsp_opt = findobj('tag','hsp_opt');
end

if findstr(cmd,'hide')
	set(hsp_opt,'Visible','off');
end

if findstr(cmd,'show')
	set(hsp_opt,'Visible','on');
	figure(hsp_opt);
end

if findstr(cmd,'get')
	h = findobj('tag','hsp_obg');
	obg = get(h,'Value');

	h = findobj('tag','hsp_oapp');
	oapp = get(h,'Value');
	h = findobj('tag','hsp_osig');
	osig = get(h,'Value');
	h = findobj('tag','hsp_ogapp');
	oglobapp = get(h,'Value') - 1;
	h = findobj('tag','hsp_oiter');
	oiter = get(h,'Value');
	h = findobj('tag','hsp_oglob');
	oglob = get(h,'Value') - 1;

	optionx = [ oapp osig oglobapp oiter oglob ];

	optiony = [ obg oapp osig ];

	h = findobj('tag','hsp_oord');
	order = get(h,'Value');

	if order == 5, order = -1; end

	h = findobj('tag','hsp_ofsig');
	specfcn = get(h,'String');

	h = findobj('tag','hsp_ofapp');
	appfcn = get(h,'String');
end
