function mf_browse(cmd)
% function mf_browse(cmd)
%
% This function handles the user selecting 'other...' from the menus
% selecting Load Routines, Fit Functions, or Fit Routines. There are
% 4 calling possibilities:
% 1. It's called by the user choosing 'other...' from one of the menus
%    In this case cmd is the relevant SecTag (see below.) The routine
%    pops up a window allowing the user to specify a new .m file
% 2. Called by the user pressing 'cancel' from the window. Window
%    closes.
% 3. Called by the user pressing 'browse...' Calls uigetfile to let user
%    choose a routine.
% 4. 'Ok' button pressed. This is the most complex action. Routine checks
%    whether user's choice is valid, and then updates the relevant menu
%    and registry variables.

%----- Set up tag names ---------------------------------------------------
SecTag   =str2mat('load routines',     'fit functions', 'fit routines');
NameTag  =str2mat('mf_LoadRoutineName','mf_FitFuncName','mf_FitRoutineName');
FileTag  =str2mat('mf_LoadRoutineFile','mf_FitFuncFile','mf_FitRoutineFile');
DirTag   =str2mat('mf_LoadRoutineDir', 'mf_FitFuncDir', 'mf_FitRoutineDir');
MenuTag  =str2mat('mf_LoadRoutineMenu','mf_FitFuncMenu','mf_FitRoutineMenu');
Type=str2mat('load routine',     'fit function', 'fit routine');

%----- If cmd is a SecTag, work out which --------------------------------
Sec=0;
for i=1:size(SecTag,1)
  if ~isempty(findstr(SecTag(i,:),cmd))
    Sec=i;
  end
end

%===== Make window ======================================================
if Sec~=0                       % cmd is a SecTag
  hmf_brows=findobj('tag','mf_BrowseWindow');
  if isempty(hmf_brows)
    mf_msg('Making browse window...');
    Bheight=str2num(get(findobj('tag','mf_TextBoxHeight'),'string'));
    hmf_brows=figure('Position',[400 400 400 4*Bheight+20],...
        'Tag','mf_BrowseWindow',...
        'MenuBar','none',...
        'Color',get(0,'DefaultUicontrolBackgroundColor'), ...
        'Resize','off',...
        'Visible','off',...
        'NumberTitle','off');

%------- ok, browse, and cancel buttons --------------------------------
     uicontrol(hmf_brows,...
        'Style','PushButton',...
        'String','Browse...',...
        'Tag','mf_browse_browse',...
        'Callback','mf_brows(''browse'')',...
        'Position',[70 4 80 Bheight]);
     uicontrol(hmf_brows,...
        'Style','PushButton',...
        'String','Ok',...
        'Tag','mf_browse_ok',...
          'Callback','mf_brows(''ok'')',...
        'Position',[160 4 80 Bheight]);
       uicontrol(hmf_brows,...
          'Style','PushButton',...
          'String','Cancel',...
          'Tag','mf_browse_cancel',...
          'CallBack','set(gcf,''visible'',''off'')', ...
        'Position',[250 4 80 Bheight]);

%----- Description, file, and directory titles ------------------------------
    uicontrol(hmf_brows,...
          'style','text',...
          'HorizontalAlignment','left',...
          'string','Description:',...
          'position',[10 3*Bheight+15 100 Bheight]);
    uicontrol(hmf_brows,...
          'style','text',...
          'HorizontalAlignment','left',...
          'string','File:',...
          'position',[10 2*Bheight+13 100 Bheight]);
    uicontrol(hmf_brows,...
          'style','text',...
          'HorizontalAlignment','left',...
          'string','Directory:',...
          'position',[10 Bheight+11 100 Bheight]);

%----- Description, file, and directory edit boxes ----------------
    uicontrol(hmf_brows,...
          'tag','mf_brows_name',...
          'style','edit',...
          'ForegroundColor',[0 0 0],...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','left',...
          'position',[120 3*Bheight+15 275 Bheight]);
    uicontrol(hmf_brows,...
          'tag','mf_brows_file',...
          'style','edit',...
          'HorizontalAlignment','left',...
          'ForegroundColor',[0 0 0],...
          'BackgroundColor',[1 1 1],...
          'position',[120 2*Bheight+13 275 Bheight]);
    uicontrol(hmf_brows,...
          'tag','mf_brows_dir',...
          'style','edit',...
          'ForegroundColor',[0 0 0],...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','left',...
          'position',[120 Bheight+11 275 Bheight]);
    set(hmf_brows,'visible','on');
    mf_msg('Done.');
  else
    figure(hmf_brows);
    delete(gca);
  end
  set(hmf_brows,...
      'Name',['MFIT: Choose new ' Type(Sec,:)],...
      'userdata',Sec,...
      'visible','on');
  set(findobj('tag','mf_brows_name'),'string','');  % Clear name
  set(findobj('tag','mf_brows_file'),'string','');  % Clear file
  set(findobj('tag','mf_brows_dir'),'string','');   % Clear dir

%===== Browse button pressed =================================
elseif strcmp(cmd,'browse')
  [file path]=uigetfiles('*.m','MFIT: Choose file','MultiSelect','off'); % Uigetfile to choose .m file
  if file~=0
    set(findobj('tag','mf_brows_name'),'string',file);  % Update name to filename
    set(findobj('tag','mf_brows_file'),'string',file);  % Update file to filename
    set(findobj('tag','mf_brows_dir'),'string',path); % Update dir to directory
  end

%===== ok button pressed ======================================
elseif strcmp(cmd,'ok')

%----- Read name,file,dir from edit boxes ----------------------------
  name=get(findobj('tag','mf_brows_name'),'string');    % Get description
  file=get(findobj('tag','mf_brows_file'),'string');    % Get filename
  if isempty(findstr(file,'.'))                 % If no .m extension add
    file=[file '.m'];
  end
  tdir =get(findobj('tag','mf_brows_dir'),'string');   % Get directory

  if isempty(dir([tdir file]))                    % Check it exists
    errordlg([tdir file ' doesn''t exist','MFIT error'])
    return
  end
  file=file(1:findstr(file,'.')-1);

%---- Work out what to update --------------------------------------------
  i=get(findobj('tag','mf_BrowseWindow'),'userdata');   % Which menu?
  hname=findobj('tag',deblank(NameTag(i,:)));         % Name registry
  hfile=findobj('tag',deblank(FileTag(i,:)));         % File registry
  hdir =findobj('tag',deblank(DirTag(i,:)));          % Dir registry
  hmenu=findobj('tag',deblank(MenuTag(i,:)));         % Menu

%----- Do the updating -----------------------------------------------------
  set(hname,'userdata',str2mat(get(hname,'userdata'),name));  % Update registries
  set(hfile,'userdata',str2mat(get(hfile,'userdata'),file));
  set(hdir, 'userdata',str2mat(get(hdir, 'userdata'),tdir));

  % Callback string for menu
  Call=[['set(findobj(''tag'',''' deblank(NameTag(i,:)) '''),''string'',''' name '''); ']...
         ['set(findobj(''tag'',''' deblank(DirTag(i,:))  '''),''string'',''' tdir '''); ']...
         ['set(findobj(''tag'',''' deblank(FileTag(i,:)) '''),''string'',''' file ''');']...
         ];
   uimenu(hmenu,'label',name,'callback',Call);          % Update menu
  set(gcf,'visible','off');
end

