function rc_inst(action)
%
% MATLAB function to display and edit instrument parameters for RESCAL.
%
%
%

if nargin==0

   action='initialise';

end

if strcmp(action,'initialise')

if ~isempty(findobj('Tag','Rescal: Instrument'))

   error(' Already running!')

end

%----- Set up figure window

Fposl=100; Fposb=100; Fwidth=550; Fheight=255;

hrc_inst_win=figure('Position',[Fposl Fposb Fwidth Fheight],...
		'NextPlot','New',...
		'Color',get(0,'DefaultUicontrolBackgroundColor'), ...
		'MenuBar','none',...
		'Name','Rescal: Instrument',...
		'NumberTitle','off',...
		'Resize','off',...
                'Tag','Rescal: Instrument', ...
		'DefaultUicontrolBackgroundColor',[1 1 1],...
		'DefaultUicontrolForegroundColor',[0 0 0],...
		'DefaultUicontrolHorizontalAlignment','left',...
		'Visible','on');

%----- Create File menu bar

hrc_inst_gpars=uimenu(hrc_inst_win,'Label','Parameters');
uimenu(hrc_inst_gpars,'Label','Get parameters','Callback','rc_getp(''ifile'')');
uimenu(hrc_inst_gpars,'Label','Save parameters','Callback','rc_savp(''ifile'');');

%----- Define parameters for text and edit windows

Tposl=10; Twidth=50; Theight=18; Tspacev=30; Tspaceh=110; Tposb= Fheight-30;
Eposl=Tposl+Twidth+5; Ewidth=50; Eheight=18; Espacev=30; Espaceh=110; Eposb=Fheight-30;
Delta=35;

%----- Source characteristics (Units: cm)
row=0;

choices=str2mat('Circular source (cm)','Rectangular source (cm)');

hrc_inst_paras(1)=uicontrol(hrc_inst_win, ...
     'Style','Pop', ...
     'String',choices, ...
     'Callback','rc_inst(''Source'')',...
     'Value',2,...
     'Position',[Tposl Tposb-row*Tspacev 3.20*Twidth Theight]);

hrc_inst_text(1)=uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Width', ...
     'Position',[Tposl+1.5*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(2)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+1.5*Espaceh Eposb-row*Espacev Ewidth Eheight]);

hrc_inst_text(2)=uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Height', ...
     'Position',[Tposl+2.5*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(3)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+2.5*Espaceh Eposb-row*Espacev Ewidth Eheight]);

%----- Guide characteristics (Units: (mins/Angs))
row=1;

choices=str2mat('No Guide','Guide  (min/Angs)');

hrc_inst_paras(4)=uicontrol(hrc_inst_win, ...
     'Style','Pop', ...
     'String',choices, ...
     'Callback','rc_inst(''Guide'')',...
     'Value',2,...
     'Position',[Tposl Tposb-row*Tspacev 3.20*Twidth Theight]);

hrc_inst_text(3)=uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','DIVH', ...
     'Position',[Tposl+1.5*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(5)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+1.5*Espaceh Eposb-row*Espacev Ewidth Eheight]);

hrc_inst_text(4)=uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','DIVV', ...
     'Position',[Tposl+2.5*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(6)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+2.5*Espaceh Eposb-row*Espacev Ewidth Eheight]);

%----- Sample geommetry (Units: cm)
row=2;

choices=str2mat('Cylindrical sample (cm)','Flat-plate sample (cm)');

hrc_inst_paras(7)=uicontrol(hrc_inst_win, ...
     'Style','Pop', ...
     'String',choices, ...
     'Callback','rc_inst(''Sample'')',...
     'Value',2,...
     'Position',[Tposl Tposb-row*Tspacev 3.20*Twidth Theight]);

hrc_inst_text(5)=uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Depth', ...
     'Position',[Tposl+1.5*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(8)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+1.5*Espaceh Eposb-row*Espacev Ewidth Eheight]);

hrc_inst_text(6)=uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Width', ...
     'Position',[Tposl+2.5*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(9)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+2.5*Espaceh Eposb-row*Espacev Ewidth Eheight]);

hrc_inst_text(7)=uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Height', ...
     'Position',[Tposl+3.5*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(10)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+3.5*Espaceh Eposb-row*Espacev Ewidth Eheight]);

%----- Detector characteristics (Units: cm)
row=3;

choices=str2mat('Circular detector (cm)','Rectangular detector (cm)');

hrc_inst_paras(11)=uicontrol(hrc_inst_win, ...
     'Style','Pop', ...
     'String',choices, ...
     'Callback','rc_inst(''Detector'')',...
     'Value',2,...
     'Position',[Tposl Tposb-row*Tspacev 3.20*Twidth Theight]);

hrc_inst_text(8)=uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Width', ...
     'Position',[Tposl+1.5*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(12)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+1.5*Espaceh Eposb-row*Espacev Ewidth Eheight]);

hrc_inst_text(9)=uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Height', ...
     'Position',[Tposl+2.5*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(13)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+2.5*Espaceh Eposb-row*Espacev Ewidth Eheight]);

%----- Mono Depth, width and height (Units: cm)
row=4;
wstretch=1.6;

uicontrol(hrc_inst_win, ...
     'Style','Text', ...
     'String','Mono (cm): ', ...
     'BackgroundColor',[0.701961 0.701961 0.701961],...
     'Position',[Tposl Tposb-row*Tspacev Twidth*wstretch Theight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Depth', ...
     'Position',[Tposl+0.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(14)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+0.78*Tspaceh Eposb-row*Espacev Ewidth Eheight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Width', ...
     'Position',[Tposl+1.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(15)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+1.78*Espaceh Eposb-row*Espacev Ewidth Eheight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Height', ...
     'Position',[Tposl+2.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(16)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+2.78*Espaceh Eposb-row*Espacev Ewidth Eheight]);

%----- Mono Depth, width and height (Units: cm)
row=5;

uicontrol(hrc_inst_win, ...
     'Style','Text', ...
     'String','Anal (cm):', ...
     'BackgroundColor',[0.701961 0.701961 0.701961],...
     'Position',[Tposl Tposb-row*Tspacev Twidth*wstretch Theight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Depth', ...
     'Position',[Tposl+0.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(17)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+0.78*Tspaceh Eposb-row*Espacev Ewidth Eheight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Width', ...
     'Position',[Tposl+1.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(18)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+1.78*Espaceh Eposb-row*Espacev Ewidth Eheight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','Height', ...
     'Position',[Tposl+2.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(19)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+2.78*Espaceh Eposb-row*Espacev Ewidth Eheight]);

%----- Distances (Units: cm)
row=6;

uicontrol(hrc_inst_win, ...
     'Style','Text', ...
     'String','Dist (cm):', ...
     'BackgroundColor',[0.701961 0.701961 0.701961],...
     'Position',[Tposl Tposb-row*Tspacev Twidth*wstretch Theight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','L0', ...
     'Position',[Tposl+0.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(20)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+0.78*Tspaceh Eposb-row*Espacev Ewidth Eheight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','L1', ...
     'Position',[Tposl+1.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(21)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+1.78*Espaceh Eposb-row*Espacev Ewidth Eheight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','L2', ...
     'Position',[Tposl+2.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(22)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+2.78*Espaceh Eposb-row*Espacev Ewidth Eheight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','L3', ...
     'Position',[Tposl+3.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(23)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+3.78*Espaceh Eposb-row*Espacev Ewidth Eheight]);

%----- Focussing (Units: m-1)
row=7;

uicontrol(hrc_inst_win, ...
     'Style','Text', ...
     'String','Focus (1/m):', ...
     'BackgroundColor',[0.701961 0.701961 0.701961],...
     'Position',[Tposl Tposb-row*Tspacev Twidth*wstretch Theight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','ROMH', ...
     'Position',[Tposl+0.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(24)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+0.78*Tspaceh Eposb-row*Espacev Ewidth Eheight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','ROMV', ...
     'Position',[Tposl+1.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(25)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+1.78*Espaceh Eposb-row*Espacev Ewidth Eheight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','ROAH', ...
     'Position',[Tposl+2.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(26)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+2.78*Espaceh Eposb-row*Espacev Ewidth Eheight]);

uicontrol(hrc_inst_win, ...
     'Style','Text',...
     'String','ROAV', ...
     'Position',[Tposl+3.78*Tspaceh Tposb-row*Tspacev Twidth Theight]);

hrc_inst_paras(27)=uicontrol(hrc_inst_win, ...
     'Style','Edit',...
     'String',[], ...
     'Position',[Eposl+3.78*Espaceh Eposb-row*Espacev Ewidth Eheight]);

%----- Store instrument parameters in Userdata of figure

uicontrol('Visible','off','Tag','hrc_inst_paras','Userdata',hrc_inst_paras)
uicontrol('Visible','off','Tag','hrc_inst_text','Userdata',hrc_inst_text)

%----- Source option

elseif strcmp('Source',action)

   hrc_inst_paras=get(findobj('Tag','hrc_inst_paras'),'Userdata');
   hrc_inst_text=get(findobj('Tag','hrc_inst_text'),'Userdata');
   value=get(hrc_inst_paras(1),'Value');

   if value == 1                           % Circular source

      set(hrc_inst_text(1),'String','Diameter')
      set(hrc_inst_text(2),'Visible','Off')
      set(hrc_inst_paras(3),'Visible','Off')      

   elseif value == 2                       % Rectangular source

      set(hrc_inst_text(1),'String','Width')
      set(hrc_inst_text(2),'Visible','On')
      set(hrc_inst_paras(3),'Visible','On')

   end

%----- Guide option

elseif strcmp('Guide',action)

   hrc_inst_paras=get(findobj('Tag','hrc_inst_paras'),'Userdata');
   hrc_inst_text=get(findobj('Tag','hrc_inst_text'),'Userdata');
   value=get(hrc_inst_paras(4),'Value');

   if value == 1                       % no Guide

      set(hrc_inst_text(3),'Visible','Off')
      set(hrc_inst_text(4),'Visible','Off')
      set(hrc_inst_paras(5),'Visible','Off')
      set(hrc_inst_paras(6),'Visible','Off')

   elseif value == 2                           % Guide

      set(hrc_inst_text(3),'Visible','On')
      set(hrc_inst_text(4),'Visible','On')
      set(hrc_inst_paras(5),'Visible','On')
      set(hrc_inst_paras(6),'Visible','On')

   end

%----- Sample option

elseif strcmp('Sample',action)

   hrc_inst_paras=get(findobj('Tag','hrc_inst_paras'),'Userdata');
   hrc_inst_text=get(findobj('Tag','hrc_inst_text'),'Userdata');
   value=get(hrc_inst_paras(7),'Value');

   if value == 1                      % Cylinder

      set(hrc_inst_text(5),'String','Diameter','Visible','On')
      set(hrc_inst_text(6),'String','Height','Visible','On')
      set(hrc_inst_text(7),'Visible','Off')
      set(hrc_inst_paras(8),'Visible','On')
      set(hrc_inst_paras(9),'Visible','On')
      set(hrc_inst_paras(10),'Visible','Off')

   elseif value == 2                   % Flat plate

      set(hrc_inst_text(5),'String','Depth','Visible','On')
      set(hrc_inst_text(6),'String','Width','Visible','On')
      set(hrc_inst_text(7),'String','Height','Visible','On')
      set(hrc_inst_paras(8),'Visible','On')
      set(hrc_inst_paras(9),'Visible','On')
      set(hrc_inst_paras(10),'Visible','On')

   end

%----- Detector option

elseif strcmp('Detector',action)

   hrc_inst_paras=get(findobj('Tag','hrc_inst_paras'),'Userdata');
   hrc_inst_text=get(findobj('Tag','hrc_inst_text'),'Userdata');
   value=get(hrc_inst_paras(11),'Value');

   if value == 1                             % Circular detector

      set(hrc_inst_text(8),'String','Diameter')
      set(hrc_inst_text(9),'Visible','Off')
      set(hrc_inst_paras(13),'Visible','Off')

   elseif value == 2                             % Rectangular detector

      set(hrc_inst_text(8),'String','Width')
      set(hrc_inst_text(9),'Visible','On')
      set(hrc_inst_paras(13),'Visible','On')

   end

end


