function mv_browse(cmd)
% function mv_browse(cmd)
%
% This function handles the user selecting 'other...' from the menus
% selecting Load Routines, Fit Functions, or Fit Routines. There are
% 4 calling possibilities:
% 1. It's called by the user choosing 'other...' from one of the menus
%    In this case cmd is the relevant SecTag (see below.) The routine
%    pops up a window allowing the user to specify a new .m file
% 2. Called by the user pressing 'cancel' from the window. Window
%    closes.
% 3. Called by the user pressing 'browse...' Calls uigetfile to let user
%    choose a routine.
% 4. 'Ok' button pressed. This is the most complex action. Routine checks
%    whether user's choice is valid, and then updates the relevant menu
%    and registry variables.

%----- Set up tag names ---------------------------------------------------
SecTag   =str2mat('load routines');
NameTag  =str2mat('mv_LoadRoutineName');
FileTag  =str2mat('mv_LoadRoutineFile');
DirTag   =str2mat('mv_LoadRoutineDir');
MenuTag  =str2mat('mv_LoadRoutineMenu');
Type=str2mat('load routine');

%----- If cmd is a SecTag, work out which --------------------------------

Sec=0;
for i=1:size(SecTag,1)
   if ~isempty(findstr(SecTag(i,:),cmd))
      Sec=i;
   end
end

%===== Make window ======================================================

if Sec~=0                               % cmd is a SecTag
   hmv_brows=findobj('tag','mv_BrowseWindow');
   if isempty(hmv_brows)
      mv_msg('Making browse window...');
      Bheight=str2num(get(findobj('tag','mv_TextBoxHeight'),'string'));
      hmv_brows=figure('Position',[400 400 400 4*Bheight+20],...
                       'Tag','mv_BrowseWindow',...
                       'MenuBar','none',...
                       'Color',get(0,'DefaultUicontrolBackgroundColor'), ...
                       'Resize','off',...
                       'Visible','off',...
                       'NumberTitle','off');

%------- ok, browse, and cancel buttons --------------------------------

      uicontrol(hmv_brows,...
                        'Style','PushButton',...
        'String','Browse...',...
        'Tag','mv_browse_browse',...
        'Callback','mv_brows(''browse'')',...
        'Position',[70 4 80 Bheight]);
      uicontrol(hmv_brows,...
        'Style','PushButton',...
        'String','Ok',...
        'Tag','mv_browse_ok',...
        'Callback','mv_brows(''ok'')',...
        'Position',[160 4 80 Bheight]);
      uicontrol(hmv_brows,...
        'Style','PushButton',...
        'String','Cancel',...
        'Tag','mv_browse_cancel',...
        'CallBack','set(gcf,''visible'',''off'')', ...
        'Position',[250 4 80 Bheight]);

%----- Description, file, and directory titles ------------------------------

      uicontrol(hmv_brows,...
      'style','text',...
      'HorizontalAlignment','left',...
      'string','Description:',...
      'position',[10 3*Bheight+15 100 Bheight]);
      uicontrol(hmv_brows,...
      'style','text',...
      'HorizontalAlignment','left',...
      'string','File:',...
      'position',[10 2*Bheight+13 100 Bheight]);
      uicontrol(hmv_brows,...
      'style','text',...
      'HorizontalAlignment','left',...
      'string','Directory:',...
      'position',[10 Bheight+11 100 Bheight]);

%----- Description, file, and directory edit boxes ----------------

      uicontrol(hmv_brows,...
                        'tag','mv_brows_name',...
      'style','edit',...
      'ForegroundColor',[0 0 0],...
      'BackgroundColor',[1 1 1],...
      'HorizontalAlignment','left',...
      'position',[120 3*Bheight+15 275 Bheight]);
      uicontrol(hmv_brows,...
      'tag','mv_brows_file',...
      'style','edit',...
      'HorizontalAlignment','left',...
      'ForegroundColor',[0 0 0],...
      'BackgroundColor',[1 1 1],...
      'position',[120 2*Bheight+13 275 Bheight]);
      uicontrol(hmv_brows,...
      'tag','mv_brows_dir',...
      'style','edit',...
      'ForegroundColor',[0 0 0],...
      'BackgroundColor',[1 1 1],...
      'HorizontalAlignment','left',...
      'position',[120 Bheight+11 275 Bheight]);
      set(hmv_brows,'visible','on');
      mv_msg('Done.');
   end

   set(hmv_brows,...
             'Name',['MVIEW: Choose new ' Type(Sec,:)],...
     'userdata',Sec,...
     'visible','on');
   set(findobj('tag','mv_brows_name'),'string',''); % Clear name
   set(findobj('tag','mv_brows_file'),'string',''); % Clear file
   set(findobj('tag','mv_brows_dir'),'string','');  % Clear dir

%===== Browse button pressed =================================

elseif strcmp(cmd,'browse')

   [file path]=uigetfile('*.m','MVIEW: Choose file'); % Uigetfile to choose .m file
   if file~=0
      set(findobj('tag','mv_brows_name'),'string',file);  % Update name to filename
      set(findobj('tag','mv_brows_file'),'string',file);  % Update file to filename
      set(findobj('tag','mv_brows_dir'),'string',path); % Update dir to directory
   end

%===== ok button pressed ======================================

elseif strcmp(cmd,'ok')

%----- Read name,file,dir from edit boxes ----------------------------

   name=get(findobj('tag','mv_brows_name'),'string');   % Get description
   file=get(findobj('tag','mv_brows_file'),'string');   % Get filename
   if isempty(findstr(file,'.'))                  % If no .m extension add
      file=[file '.m'];
   end
   tdir =get(findobj('tag','mv_brows_dir'),'string');   % Get directory

   if isempty(dir([tdir file]))                     % Check it exists
      errordlg([tdir file ' doesn''t exist','MVIEW error'])
      return
   end
   file=file(1:findstr(file,'.')-1);

%---- Work out what to update --------------------------------------------

   i=get(findobj('tag','mv_BrowseWindow'),'userdata');    % Which menu?
   hname=findobj('tag',deblank(NameTag(i,:)));          % Name registry
   hfile=findobj('tag',deblank(FileTag(i,:)));          % File registry
   hdir =findobj('tag',deblank(DirTag(i,:)));         % Dir registry
   hmenu=findobj('tag',deblank(MenuTag(i,:)));          % Menu

%----- Do the updating -----------------------------------------------------

   set(hname,'userdata',str2mat(get(hname,'userdata'),name)); % Update registries
   set(hfile,'userdata',str2mat(get(hfile,'userdata'),file));
   set(hdir, 'userdata',str2mat(get(hdir, 'userdata'),tdir));

%----- Callback string for menu

    Call=[['set(findobj(''tag'',''' deblank(NameTag(i,:)) '''),''string'',''' name '''); ']...
         ['set(findobj(''tag'',''' deblank(DirTag(i,:))  '''),''string'',''' tdir '''); ']...
         ['set(findobj(''tag'',''' deblank(FileTag(i,:)) '''),''string'',''' file ''');']...
         ];
   uimenu(hmenu,'label',name,'callback',Call);          % Update menu
   set(gcf,'visible','off');

end

