function mv_diag(action)
%
% MATLAB function to obtain required transformation of 
% the data
%
% DFM 19.5.95
%
Title='MVIEW: Transform';

%----- Check to see if any buttons are pressed

tmv_radio=get(findobj('Tag','tmv_radio'),'Userdata');
noper_buffs=length(tmv_radio);

if noper_buffs==0

   return

end

%----- Check for input arguments

if nargin==0

   action='initialise';

end

if strcmp(action,'initialise')

%----- Create figure

   boxh=20;
   Figx=200; Figy=50; Figw=200; Figh=280+boxh;
   htext=figure('Name',Title,...
		'NumberTitle','off',...
		'MenuBar','none',...
		'Color',[0.4 0.4 0.4],...
		'BackingStore','off',...
                'Tag','htext_fig',...
		'Resize','off',...
		'Visible','On');
  hp = get(htext, 'Position');
  hp = [ hp(1:2) 200 280+boxh ];
  set(htext, 'Position', hp);

%----- Create frames

   Framew=Figw-10; Frameh=135;
   Framex=5; Framey=Figh-200; 
   uicontrol(htext,'Style','Frame',...
             'Position',[Framex Framey Framew Frameh],...
             'BackgroundColor',[0 0 0])

   uicontrol(htext,'Style','Text',...
	     'Position',[20 210 Figw-30 20],...
             'String','Pre-defined transforms',...
	     'ForegroundColor',[1 1 1],...
	     'BackgroundColor',[0 0 0],...
	     'HorizontalAlignment','Center');

   Framew=Figw-10; Frameh=75;
   Framex=5; Framey=Figh-295; 
   uicontrol(htext,'Style','Frame',...
             'Position',[Framex Framey Framew Frameh],...
             'BackgroundColor',[0 0 0])

   uicontrol(htext,'Style','Text',...
	     'Position',[20 55 Figw-30 20],...
             'String','User-defined transform',...
	     'ForegroundColor',[1 1 1],...
	     'BackgroundColor',[0 0 0],...
	     'HorizontalAlignment','Center');

%----- Create text windows

   Textx=5; Texty=Figh-50; Textw=Figw-10; Texth=2*boxh;
   Text_string='Use pre-defined function, or enter a transformation in the bottom window like y=f(x,y and err)';
   uicontrol(htext,...
             'String',Text_string,...
             'Style','Text',...
	     'Position',[Textx Texty Textw Texth],...
	     'BackgroundColor',[1 1 1],...
	     'ForegroundColor',[0 0 0],...
	     'HorizontalAlignment','Center');


   Textx=10; Texty=15+boxh; Textw=Figw-20; Texth=boxh;
   uicontrol(htext,...
	     'Tag','htext_string',...	
             'Style','edit',...
	     'Position',[Textx Texty Textw Texth],...
	     'BackgroundColor',[1 1 1],...
	     'ForegroundColor',[0 0 0],...
	     'HorizontalAlignment','Left');

%----- Create 'OK' and 'Cancel' push buttons

   Butw=50; Buth=20;
   Butx=Figw/2-(Butw+10); Buty=9;
   uicontrol(htext,...
	     'Style','push',...
	     'String','OK',...
	     'Position',[Butx Buty Butw Buth],...
	     'Callback','mv_diag(''opera'')');

   uicontrol(htext,...
	     'Style','push',...
	     'String','Cancel',...
	     'Position',[Butx+Butw+20 Buty Butw Buth],...
	     'Callback','mv_diag(''killme'')');

%------ Create transformation buttons

   Butw=75; Buth=20;
   Butx=20; Buty=Figh-90-Buth;
   uicontrol(htext,...
	     'Style','Push',...
	     'String','Rebin',...
	     'Position',[Butx Buty Butw Buth],...
	     'Callback','mv_diag(''rebin'')',...
		 'ToolTipString','Enter Number or Vector in x-units ');

   uicontrol(htext,...
	     'Style','Edit',...
             'Tag','htext_rebin',...
             'BackgroundColor',[1 1 1],...
             'ForegroundColor',[0 0 0],... 
	     'Position',[Butx+Butw+10 Buty+2 Butw Buth*.85]);

   uicontrol(htext,...
	     'Style','push',...
	     'String','Rescale',...
	     'Position',[Butx Buty-8-Buth Butw Buth],...
	     'Callback','mv_diag(''rescale'')',...
		 'ToolTipString','Data multiplied by entered value');

   uicontrol(htext,...
	     'Style','Edit',...
             'String','1.0',...
             'Tag','htext_rescale',...
             'BackgroundColor',[1 1 1],...
             'ForegroundColor',[0 0 0],... 
	     'Position',[Butx+Butw+10 Buty+2-8-Buth Butw Buth*.85]);

   uicontrol(htext,...
	     'Style','push',...
	     'String','Norm',...
	     'Position',[Butx Buty-2*(8+Buth) Butw Buth],...
	     'Callback','mv_diag(''norm'')',...
		 'ToolTipString','Data normalised to entered value');

   uicontrol(htext,...
	     'Style','Edit',...
             'String','1.0',...
             'Tag','htext_norm',...
             'BackgroundColor',[1 1 1],...
             'ForegroundColor',[0 0 0],... 
	     'Position',[Butx+Butw+10 Buty+2-2*(8+Buth) Butw Buth*.85]);

   uicontrol(htext,...
	     'Style','push',...
	     'String','dy/dx',...
	     'Position',[Butx Buty-3*(8+Buth) Butw Buth],...
	     'Callback','mv_diag(''diff'')',...
		 'ToolTipString','Derivate');

elseif strcmp('opera',action)

   opera=get(findobj('Tag','htext_string'),'String');
   if ~isempty(opera)
      mv_trans(opera) ;
   end
   delete(findobj('Tag','htext_fig'));

elseif strcmp('rebin',action)

   bin_size=get(findobj('Tag','htext_rebin'),'String');
   if ~isempty(bin_size), 
      opera=['[x,y,err]=mv_rebin(x,y,err,' bin_size ')']; 
      mv_trans(opera) 
   end
   delete(findobj('Tag','htext_fig'));

elseif strcmp('rescale',action)

   norm=get(findobj('Tag','htext_rescale'),'String');
   if ~isempty(norm) 
%      opera=['norm=' norm '/max(y); '];
      opera=['norm=' norm '; '];
      opera=[opera  'y=norm*y; err=norm*err; mon=norm*mon;'];
      mv_trans(opera) 
   end
   delete(findobj('Tag','htext_fig'));

elseif strcmp('norm',action)

   norm=get(findobj('Tag','htext_norm'),'String');
   if ~isempty(norm) 
      opera=['norm=' norm '/max(y); '];
      opera=[opera  'y=norm*y; err=norm*err; mon=norm*mon;'];
      mv_trans(opera) 
   end
   delete(findobj('Tag','htext_fig'));

elseif strcmp('diff',action)

   opera='[y,x,err]=mv_dydx(x,y,err)'; 
   mv_trans(opera);   
   delete(findobj('Tag','htext_fig'));

elseif strcmp('killme',action)

   delete(findobj('Tag','htext_fig'));

end

