function hmv_data=mv_dwin(xlab, ylab, title)
%
% MFIT function  hmv_data=mv_dwin
%		Create new data window
% 		MZ 29.11.94
%
[hmv_ctrl, hmv_data]=mv_figs;

%========== Create data window ===================

if (hmv_data~=0)
   figure(hmv_data);
   xl = xlim; yl = ylim;
   cla; subplot(1,1,1);
   delete(legend);
   xlim(xl); ylim(yl);
else
   pos=[sscanf(get(findobj('tag','mv_FigurePosition'),'string'),'%d') ... 
        sscanf(get(findobj('tag','mv_FigureSize'),'string'),'%d')];
   pos=pos(:);
   bgcolor=get(findobj('tag','mv_FigureBgColor'),'string');
   hmv_data=figure('Position',pos,...
                   'Color',bgcolor,...
		   'Name','MVIEW: Data',...
       'MenuBar','none',...
       'Toolbar','figure',...
                   'Tag','MVIEW: Data',...
                   'Visible','off',...
                   'WindowButtonDownFcn','mv_btprs',...
	           'WindowButtonUpFcn',';',...
	           'Renderer','painters',...
	           'Interruptible','on');

%--------- Zoom menu ------------------------------

   hzoom=uimenu(hmv_data,'Label','Zoom');
   uimenu(hzoom,...
	'Label','Zoom in',...
	'Callback','mv_rbbox(''zoomin'')');
   uimenu(hzoom,...
	'Label','Zoom out',...
	'Callback','mv_rbbox(''zoomout'')');
   uimenu(hzoom,...
	'Label','Reset Zoom',...
	'Callback','mv_rbbox(''zoomreset'')');

%---------- Options menu-----------------------------

   haxes=uimenu(hmv_data,'Label','Axes');

   uimenu(haxes,...
         'Label','Error bars',...
         'Tag','mv_ebarsonoff',...
         'Checked','on',...
         'Callback','mv_opt(''ebars'')');

   uimenu(haxes,...
	 'Label','Grid',...
         'Tag','mv_gridonoff',...
         'Checked','on',...l
	 'Callback','mv_opt(''grid'')');

   uimenu(haxes,...
	 'Label','Log y axis',...
         'Tag','mv_logliny',...
         'Checked','off',...
	 'Callback','mv_opt(''logliny'')');

   uimenu(haxes,...
         'Label','Log x axis',...
         'Tag','mv_loglinx',...
         'Checked','off',...
	 'Callback','mv_opt(''loglinx'')');

   uimenu(haxes,...
         'Label','Axes limits',...
         'Callback','mv_xylim');

   uimenu(haxes,...
          'Label','Fix axes limits',...
          'Tag','mv_fixax',...
          'Checked','off',...
          'Callback','mv_opt(''fixax'')');

%---------- Print menu-----------------------------

   hprt=uimenu(hmv_data,'Label','Options');
   uimenu(hprt,'Label','Print figure',...
         'Callback','mv_print');
         
   uimenu(hprt, 'Tag','mv_legend', ...
      'Label', 'Legend style: on', ...
      'Callback','mv_opt(''legend'');');
   mv_opt('legend_check');
   
   uimenu(hprt, 'Label','Remove legend',...
   'Callback','legend off');
   
   uimenu(hprt,'Label','Save figure',...
       'Callback','[f,p] = uiputfile(''*.m'',''Save Figure As...'');if f,eval([''print -dmfile '' p f ]); disp(''Figure saved''); end');
end
figure(hmv_data);

%----------- Setup axes ---------------------

axescolor=get(findobj('tag','mv_AxesColor'),'string');
axesfont=get(findobj('tag','mv_AxesFont'),'string');
axesfontsize=str2num(get(findobj('tag','mv_AxesFontSize'),'string'));

hax=findobj(hmv_data, 'Type','axes');
if isempty(hax)
	hax = gca;
end
hax = hax(1);
set(hax,...
	'box','on',...
	'drawmode','fast',...
	'userdata','',...
	'xgrid','on',...
	'ygrid','on',...
	'xcolor',axescolor,...
	'ycolor',axescolor,...
	'Fontname',axesfont,...
	'HandleVisibility','on',...
	'Fontsize',axesfontsize);

%----- Axis labels and title ----------------------------------------

labelfont=get(findobj('tag','mv_LabelFont'),'string');
labelfontsize=str2num(get(findobj('tag','mv_LabelFontSize'),'string'));

if nargin<2 | (isempty(xlab) & isempty(ylab))
   xlabl='x';
   ylabl='y';
else
   xlabl=xlab;
   ylabl=ylab;
end

set(get(hax,'Title'),'String',title,'Tag','mv_text_title',...
    'Fontname',labelfont,'Fontsize',labelfontsize,'Color',axescolor,...
    'handlevisibility','on',...
    'Userdata',get(hax,'Title'));
set(get(hax,'Xlab'),'String',xlabl,'Tag','mv_text_xlabel',...
    'Fontname',labelfont,'Fontsize',labelfontsize,'Color',axescolor,...
    'handlevisibility','on',...
    'Userdata',get(hax,'Xlab'));
set(get(hax,'Ylab'),'String',ylabl,'Tag','mv_text_ylabel',...
    'Fontname',labelfont,'Fontsize',labelfontsize,'Color',axescolor,...
    'handlevisibility','on',...
    'Userdata',get(hax,'Ylab'));

set(hmv_data,'visible','on');
