function mv_text(h)
%
% MFIT function mv_text(h)
% Produce dialog to allow user to edit axis and graph titles 
% Edits string property of object with handle h
% MZ 29.11.94

%------ nargin==0 -> self call - do update ----------------
%       handle to update and string stored in userdata 

if nargin==0

	h=get(gcf,'userdata'); 
	set(h(1),'String',get(h(2),'String'));
        mv_ulabs;
	delete(gcf);
	return

elseif (h==-1)

%------ h=-1 -> self-call to select font of object --------

	h=get(gcf,'userdata'); 
	uisetfont(h(1),'Select font:');

else

%------ else make dialog box --------------
	[hmv_ctrl, hmv_data]=mv_figs;

	Str=get(h,'String');
	flag=0;
	Title='Edit text:';

	if (flag==0)
		boxh=20;
		Min=0; Max=1;
	else
		boxh=130;
		Min=0; Max=2;
	end

	htext=figure('Position',[5 320 300 30+boxh],...
					'Name',Title,...
					'NumberTitle','off',...
					'MenuBar','none',...
					'Color',[0.4 0.4 0.4],...
					'BackingStore','off',...
					'Resize','off',...
					'visible','off');

	htxt=uicontrol(htext,...
		        'Style','edit',...
	                'String',Str,...
	                'Position',[2 24 296 boxh],...
	                'BackgroundColor',[1 1 1],...
	                'ForegroundColor',[0 0 0],...
	                'Min',Min,...
	                'Max',Max,...
	                'HorizontalAlignment','Left');
	uicontrol(htext,...
	            'Style','push',...
	            'String','Font...',...
	            'Position',[75 2 50 20],...
	            'Callback','mv_text(-1)');
	uicontrol(htext,...
	            'Style','push',...
	            'String','ok',...
	            'Position',[135 2 50 20],...
	            'Callback','mv_text');
	uicontrol(htext,...
	            'Style','push',...
	            'String','Cancel',...
	            'Position',[195 2 50 20],...
	            'Callback','delete(gcf)');

	set(htext,'userdata',[h htxt],...
				'visible','on');
end
